### ISSUE TITLE
Function we can call to reset the images

### ISSUE THREAD

**Issue by fidelity2851** [yudax42/vue-upload-drop-images#10]
Pls we need a function we can call to reset the images
would be happy if u can do dis. THANKS.

**Comment by yudax42** [comment]
Hello @fidelity2851,
Thanks for suggesting this feature, i'll add it in consideration in the next update.
for now you can grab the clearButton from the DOM and use the click event like this  ` document.querySelector(".clearButton").click() ` **make sure to use it after the component is mounted** ,
Have a Great Day!
