### ISSUE TITLE
How can we show already uploaded image preview in edit form? 

### ISSUE THREAD

**Issue by B2rana** [yudax42/vue-upload-drop-images#14]
Hi,

How can we show already uploaded image preview in edit form? 
After modifying your code, I am able to show the uploaded image preview but now when I click on the "**plus**" button to add more images, it removes all the preview images.

**Comment by fidelity2851** [comment]
Hello I will advice you don't modify his code.
Just try and query out and preview your uploaded images just below his package.

**Comment by CyferZ** [comment]
Agreed, you can use another package called vueperslides if you want a slideshow preview of already uploaded images. 
Alternatively, open a "request feature" case and await feedback from the developer.

**Comment by yudax42** [comment]
Hello @B2rana.
Please provide more details of what you have changed in the code so I can know where the problem comes from, and also it's better to not modify the component code and make your images preview outside the component as @CyferZ @fidelity2851 said
Thank You!
