### ISSUE TITLE
Clear All images without using the clear all Button

### ISSUE THREAD

**Issue by fidelity2851** [yudax42/vue-upload-drop-images#15]
Guys pls how can I clear all images with out using the clear all button.
I want to clear all the images through a Vue Function  (Method)

This seems not to be working
document.querySelector(".clearButton").click()

**Comment by yudax42** [comment]
Hello @fidelity2851.

The clear all the images method is not yet implemented, I'll add it a soon as possible, meanwhile you can use `document.querySelector(".clearButton").click()` **make sure the component is mounted**
Thank you!

![vG1Xzc78V6](https://user-images.githubusercontent.com/75418209/128522558-141d6309-efa9-4fb2-85ee-d3b45999feb5.gif)

**Comment by fidelity2851** [comment]
Man this document.querySelector(".clearButton").click() works sometimes not all d time.
Is there a way to mount the components differently
