### ISSUE TITLE
how to prevent reset when hide its div ?

### ISSUE THREAD

**Issue by iftekharul-dev** [yudax42/vue-upload-drop-images#17]
i used this uploader on a step part. when i upload image  and moved to next step then back to previous this image step its gone reset. so how can i prevent this issue ..

**Comment by yudax42** [comment]
Hello @iftekharul-dev.

you can keep the state of the component using `keep-alive`, take a look at the documentation to understand more.
https://vuejs.org/v2/guide/components-dynamic-async.html 

Have a great day!

**Comment by iftekharul-dev** [comment]
Well thanx .. i used v-show instead of v-if to show each step .. now its solved.
