### ISSUE TITLE
Programmatically adding files

### ISSUE THREAD

**Issue by pshepelenko** [yudax42/vue-upload-drop-images#20]
Hi!
First of all, thank you for the component, it's awesome :-)
I have a page that allows updating an item profile: I'm getting images from the server on mount, and it would be great if I could somehow send them to your component, so a user could see the images already uploaded previously and add/delete some of them (like I can make using v-model at <b-form-input>).

BR Pavel

**Comment by CyferZ** [comment]
Hi @pshepelenko, I was curious about the same thing some time ago, but for now I'm making use of a carousel/image slider component with an event listener. 

My layout would be as follows: I have the Upload Image component above the slider, and if you have the max image prop set, just change it to get the existing amount and subtract it from the max, eg. " :max='maxAmount - existingImages.length' ". Doing this will still allow you to upload more and not go over the limit, and then the slider will get the existing images (stored in an Object, eg. existingImages) and display it as images get uploaded.

The event listener on the slider component is waiting for input that will remove the image from the slider, and send an axios request to remove it from storage, and whatever database you are making use of if it's storing the URL.

Just an idea. All the best!

**Comment by pshepelenko** [comment]
That might work, thank you :-)
