### ISSUE TITLE
add

### ISSUE THREAD

**Issue by vruzin** [yudax42/vue-upload-drop-images#3]
Good morning.

I think you need to add:
1. As soon as one picture is loaded, it must be shown, and not all at once.
2. Percentage of loading on each photo
3. Show how many photos from the total number have been uploaded
4. I consider it correct to add PHP files for the example

Thanks for the code

**Comment by yudax42** [comment]
Good morning Vruzin.

There is no server side processing in the current version, it's just client-side component that preview the uploaded images, you can listen on @change event that fired when and image is added or deleted and you can handle the upload process using axios or fetch.

Thanks for suggesting features above,  i will definitely consider adding it in the next version. have a great day!
