### ISSUE TITLE
Dragging is not working / Help

### ISSUE THREAD

**Issue by jeffersonagostinho** [yudax42/vue-upload-drop-images#5]
When I try to change the positions of the images the following error occurs

Uncaught TypeError: e.dataTransfer.files.forEach is not a function

This occurs in the DEMO version as well

**Comment by yudax42** [comment]
Hello Jeffer, 
this feature is not implemented in the current version, I'll add that functionality in the next version. but I didn't get this error, can you tell me the steps you did when that error appears. 
Thanks!

**Comment by hbakouane** [comment]
Hi @yudax42, I try to drag the file from a folder, and this error appears, thanks for this pretty package!

**Comment by yudax42** [comment]
Hello @hbakouane,
can you please tell me what is your VUE version, and what browser you used when that error appears? 
if it's possible can you record a gif or small screen recording and send it to my email yudax42@gmail.com to help me debug that problem, I did the same steps but I didn't get that weird error 😅.
Thanks for your support!

**Comment by hbakouane** [comment]
Vue 2.6.12
Chrome 90.0.4430.212

**Comment by yudax42** [comment]
Hello @hbakouane,
I tried the same chrome and VUE version but still, I didn't get that error, I updated the code and change some things that may be caused that error **please upgrade to "version": "1.0.5", and try again.**
and if you still notice that error, can you please share with me a screen recording of when that bug appears, that will help a lot.
Thanks for your time and have a great day!

**Comment by camiloserrato** [comment]
Hi @jeffersonagostinho and @yudax42 I think found the error. It happens because **e.dataTransfer.files** is **Filelist** type and you can't use forEach function on it. Yo should convert the FileList to Array like this on each instance:

<img width="687" alt="Screen Shot 2021-05-17 at 9 31 55 PM" src="https://user-images.githubusercontent.com/45015102/118581459-4efa5b00-b757-11eb-9c30-b471c93a249c.png">

**Comment by yudax42** [comment]
Hello @camiloserrato, You're right! 
can you please make a pull request?
Thanks for suggesting a solution to this problem!
