### ISSUE TITLE
How to clear all droped files?

### ISSUE THREAD

**Issue by robertotnoya** [yudax42/vue-upload-drop-images#6]
First all I'd like to congratulate you to create a easy and practical feature to Upload Images

Do you know if is possible to remove all images droped?

I'v tried to reset form but not working.

**Comment by robertotnoya** [comment]
> First all I'd like to congratulate you to create a easy and practical feature to Upload Images
> 
> Do you know if is possible to remove all images droped?
> 
> I'v tried to reset form but not working.

I create the method removeAllFiles.

thanks!

**Comment by yudax42** [comment]
Hello Robert,
I'm glad you found a solution, I will definitely consider adding this option in the future release.
Thanks for your interest!

**Comment by yudax42** [comment]
Hello again!
I added a clear all images feature to this component, please upgrade to "version": "1.0.5" and you will notice the changes.
Thanks for your suggestion!

**Comment by robertotnoya** [comment]
Thanks a lot!
Congratulations!


Em qua., 12 de mai. de 2021 às 16:54, Youssef ***@***.***>
escreveu:
