### ISSUE TITLE
Can't forEach file list

### ISSUE THREAD

**Issue by crying2812** [yudax42/vue-upload-drop-images#8]
I got error show that can forEach the e.dataTransfer.files, so i need to cast it into an array, 

`if (e && e.dataTransfer.files) {
        Array.from(e.dataTransfer.files).forEach((file) => {
          if (file.type.startsWith("image") === false) status = false;
        });
       .....
      }`

**Comment by yudax42** [comment]
Hello @crying2812,
it's fixed now, please update the package to `version:1.0.6`
Thank you for noticing this bug!
